#version: '2'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "22181:2181"
#    networks:
#      - kafka-net
#
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "29092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "control_requirement:1:1"
#    networks:
#      - kafka-net
#
#  backend:
#    build: .
#    restart: always
#    container_name: audit-application
##    environment:
##      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
##      KAFKA_TOPIC: control_requirement
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - "8085:8080"
#    networks:
#      - kafka-net
#
#networks:
#  kafka-net:
#    driver: bridge
#
#
#volumes:
#  audit-data:
#    driver: local